### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by jaybo626** [Omni-guides/Wabbajack-Modlist-Linux#10]
Did everything as the guide instructed lots of things are broken not to mention plugins vital to make the game run 🫤🤷‍♂️ properly

**Comment by Omni-guides** [comment]
Hey. You might be best to join the WJ discord and I'll help you there, but will need more information. Which guide were you following? What platform/OS are you using? Are there any errors shown when you start MO2, click play in MO2, or clicking New Game?

**Comment by Omni-guides** [comment]
Closing due to no response. Feel free to get back in touch.
