### ISSUE TITLE
SKSE can't find SkyrimSE.exe

### ISSUE THREAD

**Issue by Yoitsu** [Omni-guides/Wabbajack-Modlist-Linux#11]
Hi, I'm trying to install AVO using the generic guide, and everything has been working up until the very end:

![image](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/138531254/374f567a-b041-4f35-8c15-1cf1a5304d50)

I tried to downgrade mo2 myself from 2.5 by downloading a portable installation of 2.4.4 and copying the following from the AVO install folder:
```sh
cp -r Game\ Root mods profiles tools AVO* categories.dat ModOrganizer.ini ~/Games/AVO
```
It seems to work fine, except SKSE cant find the binary, even though it's clearly there:
![Untitled](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/138531254/4df1ad4a-3dca-4546-856f-3165c2727806)
I have skse pointing at ~/Games\AVO\mods\Skyrim Script Extender (SKSE64)\Root\skse64_loader.exe
Pointing mo2 at the steam skyrim folder results in the same problem.  I already chmod 755'd and chowned all the files. Using Proton 8.0.

**Comment by Omni-guides** [comment]
I have a .wabbajack file for a version of AVO8 using MO 2.4 - I just don't have a place to host it quite yet!

Though I haven't personally tried downgrading the MO2 version included in the official AVO WJ, it sounds like you're not far away. What is the path for the Managed Game in MO2? Under Settings, Paths tab, Managed Game?

For me that is 

```Z:\home\omni\Games\Skyrim\AVO\Game Root\SkyrimSE.exe```

**Comment by Yoitsu** [comment]
It seems to be the correct one:
![Untitled](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/138531254/af37d14f-eef9-4d3b-a4cd-6e04b0674bb6)
I noticed you mentioning a custom .wabbajack but I couldn't actually find it so I assumed it was TODO. Copying to a older mo2 version seems to work fine though, assuming this skse issue isn't because of it.

**Comment by Omni-guides** [comment]
Everything there certainly looks ok to me...

We could try and work out what is missing, or you could go grab the alternative .wabbajack file. I just uploaded it to the nexus here: https://www.nexusmods.com/skyrimspecialedition/mods/108310/

It's the first time I've uploaded anything to nexus, so please excuse how sparse the page is :D 

That .wabbajack is provided by Althro via their Discord server, and uploaded to nexus with their permission.

I'll flesh out the mod page text when I have time, but I wanted to get it online so you can get up and running.

**Comment by Yoitsu** [comment]
Awesome, it works now. I wonder if it was because I was using 2.4.4 and the custom wabbajack is on 2.4.5alpha3.  Would be nice to know for the sake of getting other modpacks to work. Thanks for the guides.

![lul2](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/138531254/bb0a810d-8f92-41b2-b73c-f8ab38e75104)
