### ISSUE TITLE
Magnum Opus - Settings

### ISSUE THREAD

**Issue by Jakkumn** [Omni-guides/Wabbajack-Modlist-Linux#16]
Since there isn't really any code to change to create a PR, just wanted to report that Fallout4 Magnum Opus worked great following the general guide. The only weirdness that I encountered was that, for some reason, the 3d rendering device selected under Fallout4Prefs.ini was a non-existant device that caused the game to not boot. Otherwise, at the time of this writing, ge-proton 9.4 seems to be working like a charm.

**Comment by Omni-guides** [comment]
Thanks for the report! It's been a long time since I tested with magnum Opus, so happy to hear it's still workable.

I can't say I've seen the issue with the 3D Rendering device before, but that's really interesting and something I will look into in case it turns out to help others in future.

**Comment by Omni-guides** [comment]
Closing as there's no real issue here :)
