### ISSUE TITLE
no Fallout 3 installation?

### ISSUE THREAD

**Issue by lothar-cell** [Omni-guides/Wabbajack-Modlist-Linux#17]
So I guess I don't need to install Fallout 3, because Wabbajack/TTW combined the two games already  into a mod on PC?

**Comment by Omni-guides** [comment]
That should be correct, yes. I believe I have it installed on Linux anyway, but once the TTW/WJ install is complete, all the interaction is with Fallout New Vegas.

**Comment by lothar-cell** [comment]
Great, thank you! I'm about the finish copying the files and the rest of the setup, pretty excited! 😁 This will be my first Fallout game ever.

**Comment by Omni-guides** [comment]
Good luck! If you get stuck, support may be easier via discord, but I understand that isn't a preference for everybody.

**Comment by lothar-cell** [comment]
Thank you! You are right, discord is more efficient in this regard👍
