### ISSUE TITLE
Getting error on every try

### ISSUE THREAD

**Issue by Dedtte** [Omni-guides/Wabbajack-Modlist-Linux#22]
I'm getting this error. I think followed all the steps as written. I'm not very well versed in Linux as the steam deck is my first Linux system.
(https://github.com/user-attachments/assets/50eff0d5-03c6-4d3b-8e57-8a5de15687a9)

**Comment by Omni-guides** [comment]
That's an interesting error, and not one I have seen so far. Troubleshooting this will be difficult over GitHub, so I would suggest you join the Wabbajack discord if you can, and I can help you there as soon as I have time.

**Comment by Omni-guides** [comment]
Is this still an issue for you?

**Comment by Dedtte** [comment]
No, fortunately I was able to find a different tutorial that worked for whatever reason. Still don't know why one worked and the other didn't.

**Comment by Omni-guides** [comment]
Out of interest, what was the different tutorial?

**Comment by Dedtte** [comment]
It was a vortex one I found on Reddit. U/brave777.

**Comment by Omni-guides** [comment]
ah, ok so not for Wabbajack modlists then.

That's fine. Happy to close this?

**Comment by Dedtte** [comment]
Yeah absolutely. Thanks so much for your help anyway
