### ISSUE TITLE
Wine Assertion issue

### ISSUE THREAD

**Issue by GrandVizierNappa** [Omni-guides/Wabbajack-Modlist-Linux#23]
I followed your guide to the letter as closely as i was able to and i keep getting this issue or error. I'm pretty sure it has something to do with not being able to run something behind Vulcan but i am unsure on how to figure out what
![Screenshot_20241022_005456](https://github.com/user-attachments/assets/50d3da4a-e7c9-4c0e-b750-888c6e995f64)

**Comment by Omni-guides** [comment]
This happens with some AMD GPUs it seems. To resolve it, run your equivalent of the following command:

`echo "dxvk.enableGraphicsPipelineLibrary = False" >"$modlist_gamedir/dxvk.conf"`

So for you (taking the path from your error message), the command would be:

```
echo "dxvk.enableGraphicsPipelineLibrary = False" >"/home/garyn/GameM.2/WabbaDownload/Game Root/dxvk.conf"
```

**Comment by GrandVizierNappa** [comment]
> This happens with some AMD GPUs it seems. To resolve it, run your equivalent of the following command:
> 
> `echo "dxvk.enableGraphicsPipelineLibrary = False" >"$modlist_gamedir/dxvk.conf"`
> 
> So for you (taking the path from your error message), the command would be:
> 
> ```
> echo "dxvk.enableGraphicsPipelineLibrary = False" >"/home/garyn/GameM.2/WabbaDownload/Game Root/dxvk.conf"
> ```

Cool will try this and will let you know what happens
