### ISSUE TITLE
SKSE unable to find SkyrimSE.exe

### ISSUE THREAD

**Issue by ComradeClaritux** [Omni-guides/Wabbajack-Modlist-Linux#25]
I've been trying to set up both Tuxborn and Nordic Souls on my computer running latest Bazzite image, and in both cases I've run into an issue where upon launching I get an error box telling me SKSE is unable to find SkyrimSE.exe. All paths in MO2 seem to be correct according to the guides. In both cases the workaround that fixed it for me was disabling SKSE and SKSE ini file (don't know if the latter is necessary) in MO2 and do a manual SKSE install by copying the files from their mods folders into Game Root (or Game Root/Data) and adding SKSE as a new shortcut in MO2. Then everything works as it should. Install method was with Wabbajack via the Wine guide, adding MO2 to Steam and running the install script (which completed successfully)

**Comment by Omni-guides** [comment]
For some reason, Bazzite seems to behave a bit differently than all other distros, for various things I've come across as reports from users. Even down to the user home directory actually being located in /var, for whatever reason.

It sounds like (if manually copying skse64_loader.exe into Game Root fixes things) that RootBuilder isn't managing to do it's thing, which would also be unique to Bazzite in my experience.

**Comment by ComradeClaritux** [comment]
Yes, I was kinda starting to suspect it could be some weird symlinking issue, so I tried opening modorganizer.ini and find and replace all: Z:/home --> Z:/var/home and Z:\\\home --> Z:\\\var\\\home and hey presto, now it works! =) This fix probably applies to Fedora Silverblue and Kinoite as well

**Comment by Omni-guides** [comment]
Glad you got it working. I wonder if Proton just isn't following the symlink properly (from /home/user to /var/home/user). Perhaps there's a way to make sure Proton does so, or perhaps another option would be to mount the /var/home path as a new drive inside the prefix via protontricks/winetricks.. or just make sure to use the real path instead, as you have done  :)

Would be hard to automate that in my installation script only for specific distros, but I'll have a think.

Main thing is you are up and running.
