### ISSUE TITLE
MO2 closes when clicking anywhere in the window 

### ISSUE THREAD

**Issue by slurrps-mcgee** [Omni-guides/Wabbajack-Modlist-Linux#26]
The script seems to run successfully however I get a proton trick warning saying it doesn't have access to the /run/media/deck/mod games folder and when clicking on steam entry for MO2 is launches but when I try and start it immediately closes.

**Comment by Omni-guides** [comment]
If /run/media/deck/mod is where your modlist is, you will need to add permissions for this using either protontricks --override, or via the flatseal GUI app if you prefer. I'm assuming that /run/media/deck/mod is your SDCard - I wouldn't recommend using an external drive for this, for example. Are you using the touchscreen or the mouse pointer to click Play in MO2? Are you in Desktop or game mode? Which modlist are you trying to run?

If you need more help, support is far easier using the Discord channel. You can also attach the log file created by the script, which should be located at /home/deck/omni-guides-sh.log.

**Comment by Omni-guides** [comment]
No response so I'm closing this. Feel free to reach out if you still need help.

**Comment by slurrps-mcgee** [comment]
My apologies I didn't see the notification. I was able to get it running it seems it was because I was on desktop mode

**Comment by Omni-guides** [comment]
No worries, glad you got it up and running!
