### ISSUE TITLE
why can't we install webview through bottles when I see a button?

### ISSUE THREAD

**Issue by this-is-just-con-tribute** [Omni-guides/Wabbajack-Modlist-Linux#27]
Edit: just found out on discord that it's massively out of date. I think it would help avoid confusion if you mentioned this in the guide.

Also, Kron4ek wasn't an option, so I just used proton. I had to update it using the included Proton Plus utility Nobara provided, but it worked, and I changed my runner from ancient wine to GE-Proton9-20.

**Comment by Omni-guides** [comment]
You need to add the Kron4ek runner using bottles preferences -> Runners. Proton will not work - the nexus login will fail. Hopefully this will become an option with Proton 10 early next year, but  we will see.

Proton GE 9.20 is still based on Wine 9.0.

Anyway, as per our chat in Discord, you are trying to install the GOG version of a list, which I do not currently cater for with this method.
