### ISSUE TITLE
Begin Again through VM method

### ISSUE THREAD

**Issue by romanovzky** [Omni-guides/Wabbajack-Modlist-Linux#28]
Hi Omni,

I was trying to get Begin Again working without dual booting (as I'm deprecating Windows altogether and my Steam library is my home folder under an EXT4 partition), and I'm having a lot of issues.

My first attempt was via Wabbajack on wine (which has worked great for multiple Skyrim modlists), but when I run the Tales of Two Wastelands installer it either crashes halfway through because of audio recoding or (if I run without the recoding) it crashes in the end.

Then I decided to spin my Win10 VM (on QEMU/KVM) which sees some Linux folders through network drives via SAMBA. Wabbajack works fine, but then the TTW installer does not see the network drives when I'm looking for the path to the games.

Any idea on how I could work around this?

Cheers

**Comment by Omni-guides** [comment]
You would be better off asking this in the Wabbajack discord Linux channel. I don't have much exposure to FNV lists, but I believe Sulfur has a method for installing TTW based lists entirely on Linux.

**Comment by romanovzky** [comment]
Will do, cheers mate
