### ISSUE TITLE
Permission error when launching the game

### ISSUE THREAD

**Issue by zdaar** [Omni-guides/Wabbajack-Modlist-Linux#3]
Hi !
Thanks for an amazing writeup.
I have an issue when starting the game on Septimus4. 
It seems that some kind of python script has a permission error.

![image](https://user-images.githubusercontent.com/4218386/198910824-10b3c97d-763d-4db5-b9d3-f102ea490978.png)

Think you could help me debug it ?

Additional info : I even tried chmod -R 777 the entire root folder, and chowned it to deck

Thanks in advance

**Comment by Omni-guides** [comment]
Hello! :)

This error can apparently be ignored. It also happens on Windows. I'd love to be able to get a fix for it, as it can cause issues having to switch the focused window on the SteamDeck .. but at least it can be closed and ignored.

There are a few other additional steps required for Septimus 4, vs Septimus 3 - For one, you need to install vcredist2022 into the proton prefix (2019 is not enough). I was hoping to form a one-liner for doing that, but haven't had time to investigate. For now, I copy the vcredist installer to somewhere inside the Prefix, then use protontricks to enter the shell (protontricks <ID> shell) and then run the installer (wine ../path/to/installer.exe) - it's very quick, but I was hoping to cut this down to one single line.

The bonus after that is that only ENB should to be disabled (feel free to play with the Linux version of ENB ;) ) - all other mods appear to be compatible. I will caveat this in that I haven't had time to play deep into the game, so there may be issues lurking around the corner.

My plan will be to update the writeup with Septimus 4 as a baseline - hopefully I'll find time to do so soon :)

**Comment by Omni-guides** [comment]
Alright, I've updated the guide with the steps for Septimus 4. This particular error can apparently be ignored and closed, and though I'd like to find a fix for it, it also happens on Windows, so isn't related specifically to running Wabbajack Modlists on Linux, so I@m closing this issue.
