### ISSUE TITLE
Welcome to Paradise: CTD in MCM Config menu with new game

### ISSUE THREAD

**Issue by dfarley1** [Omni-guides/Wabbajack-Modlist-Linux#6]
I've been following the WTP guide to get it working on my Deck. On my PC, the game runs and mods work, at least up through opening the vault (with Start Me Up).

However, on my Deck, the game will crash to desktop when opening the MCM Config menu. I don't know how to diagnose crashes other than toggling mods on/off several at a time. Any suggestions?

**Comment by Omni-guides** [comment]
Yep, just disable the MCM Boost mod in MO2 and you should be good to go. The mod is designed to increase the loading speed of the MCM, but for some reason just doesn't work via Proton. 

Unless you are in and out of the MCM all the time, I doubt it will have a big impact on the game.

**Comment by brianx87** [comment]
That's awesome, fixed it for me.

**Comment by Omni-guides** [comment]
Added a section to the Welcome to Paradise Guide to cover this. Closing.
