### ISSUE TITLE
Proper display scaling

### ISSUE THREAD

**Issue by brianx87** [Omni-guides/Wabbajack-Modlist-Linux#7]
I'm having trouble getting the game to scale properly in fullscreen without side bars or the image being over cropped and the power armor is over cropped no matter what the settings are, can you provide the correct ini settings or which mods to disable to correct the display please.

What is the correct location for the ini's as there are several, there is fallout4prefs.ini located in the fallout 4 install folder which is the one the game appears to be running of , one in the My Documents located in the compatdata folder and the one accessed by ini editor in mo2 and the WTP mod folder ini. The ini that's in use located in the install folder at `/home/deck/.local/share/Steam/steamapps/common/Fallout 4/Fallout4/` keeps reverting the settings too.

**Comment by brianx87** [comment]
Scaling issues fixed by disabling High FPS Physics Fix - WTP Settings

**Comment by Omni-guides** [comment]
You shouldn't have to disable that mod entirely (it's not really a mod, just makes MO2 include pre-defined settings).

You should be able to just edit the settings. Double click on "High FPS Physics -WTP Settings", then click the "INI Files " tab, and finally click the only item listed under "INI Files" on the left. That should show you the included settings of that file on the right, allowing you to make alterations - it may be as simple as changing Fullscreen to true. Click 'Close' to close that window and it should prompt you to save the changes.

![WTP-FO4FullScreen](https://github.com/Omni-guides/Wabbajack-Modlist-Linux/assets/110171124/abdf9352-4666-475f-8df3-47d9c1603fb5)

Re-enable the "High FPS Physics -WTP Settings" mod in MO2 if you still have it disabled, and you should be good to go.

Let me know how you get on, and if it fixes your issue, I'll add a section to the guide to detail this change.

**Comment by Omni-guides** [comment]
Added a section in the guide for WTP to cover this. Closing.
