### ISSUE TITLE
Duplicate Game Files

### ISSUE THREAD

**Issue by ayanami3** [Omni-guides/Wabbajack-Modlist-Linux#8]
I used this guide as a base for Viva New Vegas, I just made my own "Stock Game" directory. Everything works fine, but this directory is essentially a duplicate of the game install directory. Is there any way around using this as the game directory?

**Comment by Omni-guides** [comment]
You could try just overwriting the vanilla game dir contents with your Stock Game folder contents. However, i have to admit that FN3/NV has been far more fussy when getting things to run on Linux/Deck, compared to FO4 or Skyrim.

If you do, then just make sure the Game Path and Executables paths all match up with where the executables exist.

**Comment by Omni-guides** [comment]
Closing as no follow up. Feel free to reach out if you try it and need help.
